export default [
    {
        id: 1,
        name: 'The Willos',
        image: 'https://www.eltiempo.com/uploads/2021/11/30/61a6a7be898cb.jpeg',
        direction: '3517 W. Gray St. Utica',
        rooms: 3,
        bathroom: 2,
        superfice: '230 ft2',
        cost: '$440/m',
    },
    {
        id: 2,
        name: 'Orchard House',
        image: 'https://static.construible.es/media/2020/07/edificio-puerta-alicante-elche-obtiene-certificacion-verde-3-hojas-2.png',
        direction: '3517 W. Gray St. Utica',
        rooms: 3,
        bathroom: 2,
        superfice: '230 ft2',
        cost: '$440/m',
    },
    {
        id: 3,
        name: 'Orchard House',
        image: 'https://static.construible.es/media/2020/07/edificio-puerta-alicante-elche-obtiene-certificacion-verde-3-hojas-2.png',
        direction: '3517 W. Gray St. Utica',
        rooms: 3,
        bathroom: 2,
        superfice: '230 ft2',
        cost: '$440/m',
    },
    {
        id: 4,
        name: 'The Willos',
        image: 'https://www.eltiempo.com/uploads/2021/11/30/61a6a7be898cb.jpeg',
        direction: '3517 W. Gray St. Utica',
        rooms: 3,
        bathroom: 2,
        superfice: '230 ft2',
        cost: '$440/m',
    },
    {
        id: 5,
        name: 'Corner House',
        image: 'https://laboratorio.latercera.com/wp-content/uploads/2019/06/portada-1.jpg',
        direction: '3517 W. Gray St. Utica',
        rooms: 3,
        bathroom: 2,
        superfice: '230 ft2',
        cost: '$440/m',
    },
]